# Generated by Django 3.0.6 on 2020-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('database_config', models.CharField(max_length=100)),
                ('database_type', models.CharField(max_length=100)),
                ('database_desctiption', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'databse_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='databaseConfig',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
